language: bash
services: docker

env:
  - SUBDIR=9.6/2.4
  - SUBDIR=9.6/2.3
  - SUBDIR=9.5/2.4
  - SUBDIR=9.5/2.3
  - SUBDIR=9.5/2.2
  - SUBDIR=9.4/2.4
  - SUBDIR=9.4/2.3
  - SUBDIR=9.4/2.2
  - SUBDIR=9.3/2.4
  - SUBDIR=9.3/2.3
  - SUBDIR=9.3/2.2
  - SUBDIR=10/2.4


install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - image="postgis:${SUBDIR/\//_}"

script:
  - travis_retry docker build -t "$image" -f "$SUBDIR"/Dockerfile .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images
